# Generated by Django 4.0.5 on 2023-03-29 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 5, 50, 743272)),
        ),
    ]
