# Generated by Django 4.0.5 on 2023-03-29 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_cart_product_cart_product'),
        ('order', '0005_alter_orderitem_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 18, 57, 40, 272890)),
        ),
        migrations.AlterField(
            model_name='update_order',
            name='product',
            field=models.ManyToManyField(to='product.cart'),
        ),
    ]
